# Generated by Django 5.1.7 on 2025-03-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randomchats", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
