services:
  web:
    build: .
    deploy:
      replicas: 3
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 findyourmatch.asgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      STATIC_ROOT: ${STATIC_ROOT}
      MEDIA_ROOT: ${MEDIA_ROOT}
    networks:
      - findyourmatch_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 3
      timeout: 5s

  postgres_db:
    image: postgres:15
    container_name: findyourmatch_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - findyourmatch_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U findyourmatch -d findyourmatch_db"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:alpine
    container_name: findyourmatch_redis
    ports:
      - "6379:6379"
    networks:
      - findyourmatch_network
    restart: always

  nginx:
    image: nginx
    container_name: findyourmatch_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      web:
        condition: service_healthy
    networks:
      - findyourmatch_network
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  findyourmatch_network:
    driver: bridge