# Generated by Django 5.1.7 on 2025-03-20 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userprofile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccountsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_account_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userinteractions",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userlike",
            name="user_interactions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.userinteractions",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_users", to="userprofile.interest"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="languages_spoken",
            field=models.ManyToManyField(
                blank=True, related_name="speakers", to="userprofile.language"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userlike",
            name="liked_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userinteractions",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_by",
                through="userprofile.UserLike",
                to="userprofile.userprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userlike",
            unique_together={("user_interactions", "liked_profile")},
        ),
    ]
