# Generated by Django 5.1.7 on 2025-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='categories',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='user_interests', to='userprofile.interest'),
        ),
    ]
