# Generated by Django 5.1.7 on 2025-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_interest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pets',
        ),
    ]
